Игра, измеряющая скорость печати. 
Время начинается автоматически с началом печати.
У тебя есть 60 секунд.

<a href="https://trackgit.com">
<img src="https://us-central1-trackgit-analytics.cloudfunctions.net/token/ping/lx8ksv2dkqu65o7mczal" alt="trackgit-views" />
</a>

[![Hits](https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgithub.com%2FGrudininaStacy%2FSpeedType&count_bg=%2379C83D&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=page+views&edge_flat=false)](https://hits.seeyoufarm.com)

